import Head from "next/head";
import Getstarted from "../component/Getstarted";
import SignUp from "../component/Signup";

export default function Home() {
  <Head>
    <title>2go</title>
    <meta name="description" content="Generated by create next app" />
    <link
      rel="icon"
      href="https://mir-s3-cdn-cf.behance.net/projects/max_808/ba2df257215135.Y3JvcCw3MDksNTU1LDAsMA.png"
    />
  </Head>;
  const user = true;
  return <div>{user ? <Getstarted /> : <SignUp />}</div>;
}
