import Head from "next/head";
import Link from "next/link";
import Chat from "../component/Chat";
import Chats from "../component/Chats";
import Preloader from "../component/Preloader";
import StatusUpdates from "../component/Status";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>2go</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://mir-s3-cdn-cf.behance.net/projects/max_808/ba2df257215135.Y3JvcCw3MDksNTU1LDAsMA.png"
        />
      </Head>
      <div>
        <div className={styles.header}>
          <h2>2GO</h2>
          <div className={styles.profile__icon}>
            <Link href="/profile">
              <img
                src="https://www.irishexaminer.com/cms_media/module_img/275/137630_1_seoimage16x9_ie-401163_4bad92fd00a3493386706e00704e3488.jpg"
                alt=""
              />
            </Link>
          </div>
        </div>
        <div className={styles.input_section}>
          <input type="text" placeholder="search for chat" />
        </div>
      </div>
      <StatusUpdates />
      <Chats />
      <Chat />
    </div>
  );
}
